import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "RobIA",
  description: "Generated by create next app",
  themeColor: "#E5E3D9",
};

export const viewport: Viewport = {
	themeColor: '#E5E3D9',
}

export default function RootLayout({ children, }: 
	Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="en">
		<body>
			{children}
		</body>
		</html>
	);
}
